### ISSUE TITLE
README sections to be updated with install instructions

### ISSUE THREAD

**Issue by sherebiahtishbi** [sermonindex/sermondownloader2.0#1]
Bro will you be able contribute towards the instructions for Mac? I will take care of Linux and we would need someone to help is with instructions for windows. Lets prayerfully plan to release it in day or two.

**Comment by sermonindex-dev** [comment]
brother,  yes I can definetly do instructions for the mac.  I can get someone to help with windows no problem!

**Comment by vincentlarkin** [comment]
Done. 3d9da2d8e232febd39f324de577003e055214f4f 

Have built Mac installer but I'm getting an error when running it. Will try to fix it, hopefully I can publish it in a few days

**Comment by sermonindex-dev** [comment]
Great to hear this. looking forward to testing out the mac installer.
